name: schulplaner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.1+1
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5
  flutter_lucide: ^1.4.0
  gradient_borders: ^1.0.1
  provider: ^6.1.2
  equatable:
    git: https://github.com/felangel/equatable.git

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
