name: schulplaner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lucide: ^1.6.1
  mesh: ^0.4.2
  equatable:
    git: https://github.com/felangel/equatable.git
  uuid: ^4.5.1
  intl: any
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  email_validator: ^3.0.0
  flutter_svg: ^2.0.16
  flutter_expandable_fab: ^2.3.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  logger: ^2.5.0
  flutter_markdown: ^0.7.4
  
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_vertexai: ^1.0.4
  # firebase_messaging: ^15.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/app_config/